import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavLinks from "./NavLinks";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "My Next.js App",
    template: "%s | PageCuy",
  },
  description: "Generated by create next app",
};


export default function RootMarketLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <header>
          <div className="flex items-center justify-between p-4 bg-transparent ">
            <h1 className="text-xl font-bold">My Next.js App</h1>
            <NavLinks />
          </div>
        </header>
        <main className="w-6xl mx-auto py-8 min-h-[100dvh]">
          {children}
        </main>
        <footer>
          <div className="flex items-center justify-center p-4 bg-linear-to-b/hsl from-transparent to-slate-950">
            <p className="text-sm text-gray-600 dark:text-gray-400">
              © 2023 My Next.js App. All rights reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
